### ISSUE TITLE
Paul zobs Web Design II 020

### ISSUE THREAD

**Issue by paulzobs** [paulzobs/modularity-mindfulness#1]
I thought I set up my index properly but keep getting these index errors, could you help explain them?
<img width="518" alt="Screen Shot 2020-09-29 at 3 22 46 PM" src="https://user-images.githubusercontent.com/55509579/94606303-4573bf80-0268-11eb-918a-d616a2a063e7.png">
@hellachella

**Comment by hellachella** [comment]
`<header role="banner">` Roles tell screen readers what is what on your page. It is literally just labelling everything for a screen reader menu using proper landmark roles. If you look at the notes pdf I uploaded to Slack, the landmark roles are listed. 

So basically you haven't defined Landmark roles yet in your HTML.

**Comment by hellachella** [comment]
Could I say the term "landmark roles" again? Absolutely I could. 

Landmark Roles. 

I need coffee.

**Comment by paulzobs** [comment]
Lmao awesome thank you
